# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/peripheral_course_lab1/ip_repo/edit_PWM_w_Int_v1_0.cache/wt [current_project]
set_property parent.project_path c:/peripheral_course_lab1/ip_repo/edit_PWM_w_Int_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Peripheral_course_lab1/ip_repo/PWM_w_Int_1.0
  myip_1.0
  c:/Peripheral_course_lab1/ip_repo
} [current_project]
read_verilog -library xil_defaultlib {
  c:/peripheral_course_lab1/ip_repo/pwm_w_int_1.0/hdl/PWM_w_Int_v1_0_S00_AXI.v
  c:/peripheral_course_lab1/ip_repo/pwm_w_int_1.0/hdl/PWM_w_Int_v1_0.v
  c:/peripheral_course_lab1/ip_repo/edit_PWM_w_Int_v1_0.srcs/sources_1/new/PWM_Controller_Int.v
}
synth_design -top PWM_w_Int_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef PWM_w_Int_v1_0.dcp
catch { report_utilization -file PWM_w_Int_v1_0_utilization_synth.rpt -pb PWM_w_Int_v1_0_utilization_synth.pb }
