# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/18131/Desktop/task2/task2_project/ip_repo/edit_UART_IP_v1_0.cache/wt [current_project]
set_property parent.project_path C:/Users/18131/Desktop/task2/task2_project/ip_repo/edit_UART_IP_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/18131/Desktop/task2/task2_project/ip_repo/UART_IP_1.0 [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/18131/Desktop/task2/task2_project/ip_repo/uart_ip_1.0/hdl/UART_IP_v1_0_S00_AXI.v
  C:/Users/18131/Desktop/task2/uart_source/transmit.v
  C:/Users/18131/Desktop/task2/uart_source/reciever.v
  C:/Users/18131/Desktop/task2/uart_source/BaudRate.v
  C:/Users/18131/Desktop/task2/task2_project/ip_repo/uart_ip_1.0/hdl/UART_IP_v1_0.v
}
synth_design -top UART_IP_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef UART_IP_v1_0.dcp
catch { report_utilization -file UART_IP_v1_0_utilization_synth.rpt -pb UART_IP_v1_0_utilization_synth.pb }
